### ISSUE TITLE
Exception when scrolling to WebComponent

### ISSUE THREAD

**Issue by EbisuGit** [webdriverextensions/webdriverextensions#111]
When using Bot.scrollTo(_**X extends WebComponent**_) exception is thrown:

java.lang.IllegalArgumentException: Argument is of an illegal type: X.
	at org.openqa.selenium.remote.internal.WebElementToJsonConverter.apply(WebElementToJsonConverter.java:84)
	at com.google.common.collect.Iterators$6.transform(Iterators.java:820)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48)
	at com.google.common.collect.Iterators.addAll(Iterators.java:373)
	at com.google.common.collect.Lists.newArrayList(Lists.java:165)
	at com.google.common.collect.Lists.newArrayList(Lists.java:150)
	at org.openqa.selenium.remote.RemoteWebDriver.executeScript(RemoteWebDriver.java:580)
	at com.github.webdriverextensions.Bot.executeJavascript(Bot.java:281)
	at com.github.webdriverextensions.Bot.scrollTo(Bot.java:274)

Tested on Ubuntu 16.04 x64, happens with all drivers.

**Comment by andidev** [comment]
Okey so i think the Bot.scrollTo needs to pass the wrappedWebElement inside the WebComponent to the executeJavascript(...) method.

**Comment by andidev** [comment]
Released in version 3.8.1
