### ISSUE TITLE
 WebDriver com.github.webdriverextensions.WebComponent.getWrappedDriver() method of WebComponent class is not returning the WebDriver instance

### ISSUE THREAD

**Issue by bharathishjava** [webdriverextensions/webdriverextensions#125]
Hi,
I wanted to create my own custom WebElement implementation, so tha I can use explicit waits there. but when I tried to get the WebDriver instance by calling getWrappedDriver() method am getting following error.
java.lang.ClassCastException: com.sun.proxy.$Proxy7 cannot be cast to org.openqa.selenium.internal.WrapsDriver
	**at com.github.webdriverextensions.WebComponent.getWrappedDriver(WebComponent.java:259)**
	at cuctomElements.MyElement.doubleClick(MyElement.java:28)
	at test.GoogleTest.test(GoogleTest.java:39)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

**MyElement class**

import java.util.concurrent.TimeUnit;

import org.openqa.selenium.NoSuchElementException;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebDriverException;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.FluentWait;

import com.github.webdriverextensions.WebComponent;

public class MyElement extends WebComponent {
	private FluentWait<WebDriver> waiter;
	private Actions actions;

	public void doubleClick() {
		getAction(getWrappedDriver()).doubleClick(getWrappedWebElement()).build().perform();
	}

	public FluentWait<WebDriver> getWaiter(WebDriver driver) {
		if (waiter == null)
			waiter = new FluentWait<>(driver).withTimeout(10, TimeUnit.SECONDS).pollingEvery(2, TimeUnit.SECONDS)
					.ignoring(NoSuchElementException.class).ignoring(WebDriverException.class);
		return waiter;
	}
	
	public Actions getAction(WebDriver driver) {
		if(actions==null)
			actions = new Actions(driver);
		return actions;
	}
}

Can somebody help please.

Thank you,

**Comment by andidev** [comment]
Yeah this is a bug in the WebComponent class. The web element needs to be casted to WrapsElement before and getWrappedElement() needs to be called before doing the WrapsDriver cast. I will release a patch release 3.11.1 to fix this right away.

**Comment by javydreamercsw** [comment]
Any reason why this is not on Maven central yet?

**Comment by andidev** [comment]
Strange, I'll try to release it again

**Comment by andidev** [comment]
3.11.2 released and confirmed it is in repo
