### ISSUE TITLE
Generic type lists implementing WebComponent

### ISSUE THREAD

**Issue by gunnee** [webdriverextensions/webdriverextensions#50]
The following constellation where a generic type is used currently fails:
```java
public class TableComponent<T extends WebComponent> extends WebComponent {
	
	@FindBy(xpath = "//table[@class='apexir_WORKSHEET_DATA']/tbody/tr")
	public List<T> rowList;
	
}
```
I currently don't see any way to get this working. During WebComponent assignment checks, the specific type is not available and the check of type T fails.
```
java.lang.ClassCastException: sun.reflect.generics.reflectiveObjects.ParameterizedTypeImpl cannot be cast to java.lang.Class
	at com.github.webdriverextensions.WebDriverExtensionFieldDecorator.isDecoratableWebComponentList(WebDriverExtensionFieldDecorator.java:96)
	at com.github.webdriverextensions.WebDriverExtensionFieldDecorator.decorate(WebDriverExtensionFieldDecorator.java:54)
	at org.openqa.selenium.support.PageFactory.proxyFields(PageFactory.java:112)
	at org.openqa.selenium.support.PageFactory.initElements(PageFactory.java:104)
	at com.github.webdriverextensions.WebPage.initElements(WebPage.java:19)
	at com.github.webdriverextensions.internal.ObjectPool.getPageObject(ObjectPool.java:38)
	at com.github.webdriverextensions.WebDriverExtensionFieldDecorator.decorate(WebDriverExtensionFieldDecorator.java:61)
	at org.openqa.selenium.support.PageFactory.proxyFields(PageFactory.java:112)
	at org.openqa.selenium.support.PageFactory.initElements(PageFactory.java:104)
	at com.github.webdriverextensions.junitrunner.WebDriverRunner.createTest(WebDriverRunner.java:172)
	at org.junit.runners.BlockJUnit4ClassRunner$1.runReflectiveCall(BlockJUnit4ClassRunner.java:244)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.BlockJUnit4ClassRunner.methodBlock(BlockJUnit4ClassRunner.java:241)
	at com.github.webdriverextensions.junitrunner.WebDriverRunner.runChild(WebDriverRunner.java:271)
	at com.github.webdriverextensions.junitrunner.WebDriverRunner.runChild(WebDriverRunner.java:86)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
```
Maybe someone has a solution on how to improve..

**Comment by andidev** [comment]
Great catch!
I think I have the solution. The current generic type argument could be saved in the WebDriverExtensionsFieldDecorator. In that way it will be available when needed.

I'll try to implement it.

**Comment by andidev** [comment]
So I think your use case should work now, could you please confirm that version 1.5.0-SNAPSHOT fixes your issues?

you can install version 1.5.0-SNAPSHOT in your local maven repo by running
```bash
git co 1.X.X
git pull
mvn clean install
```

As soon as you confirm that it works I'll make a release.

**Comment by gunnee** [comment]
Works perfectly. Note that you still use an old version of property 'webdriverextensions-maven-plugin.version' inside the pom.xml. Thank you very much.

**Comment by andidev** [comment]
Thanks! Great then I'll try to release it.

Yes thats true, I'll change to the latests version as well.

**Comment by andidev** [comment]
So it's released. It takes some time before it is synced and available in the maven repo.
