### ISSUE TITLE
Desired Capabilities for IE is not effective in the driver which resulted into exception

### ISSUE THREAD

**Issue by ramkumary** [webdriverextensions/webdriverextensions#88]
I have created an IE Capabilities Class and passed the same in the method. 

```
public class InternetExplorerCapabilities extends DesiredCapabilities {
	private static final long serialVersionUID = -7497157939360194853L;
	final static String IE_WEBDRIVER_BINARY_PATH_PROPERTY = "webdriver.ie.driver";
	public InternetExplorerCapabilities() {
		DesiredCapabilities standardCapabilities = DesiredCapabilities.internetExplorer();
		standardCapabilities.setCapability(InternetExplorerDriver.INTRODUCE_FLAKINESS_BY_IGNORING_SECURITY_DOMAINS,
				true);
		standardCapabilities.setCapability(InternetExplorerDriver.UNEXPECTED_ALERT_BEHAVIOR, "ignore");
		standardCapabilities.setCapability(InternetExplorerDriver.ENABLE_PERSISTENT_HOVERING, false);
		standardCapabilities.setCapability(InternetExplorerDriver.IE_ENSURE_CLEAN_SESSION, true);
		System.setProperty(IE_WEBDRIVER_BINARY_PATH_PROPERTY, "drivers/internetexplorerdriver-windows-32bit.exe");
	}
}

@RunWith(WebDriverRunner.class)
@InternetExplorer(desiredCapabilitiesClass = InternetExplorerCapabilities.class)
public class LoginPageTest {
	LoginPage loginPage;
```

**Exception**
org.openqa.selenium.SessionNotCreatedException: Unexpected error launching Internet Explorer. Protected Mode settings are not the same for all zones. Enable Protected Mode must be set to the same value (enabled or disabled) for all zones. (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 0 milliseconds
Build info: version: '3.3.1', revision: '5234b325d5', time: '2017-03-10 09:10:29 +0000'
System info: host: '', ip: '', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_102'
Driver info: driver.version: InternetExplorerDriver
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:216)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:168)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:367)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:113)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:141)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:82)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:604)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:244)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:230)
	at org.openqa.selenium.ie.InternetExplorerDriver.run(InternetExplorerDriver.java:180)
	at org.openqa.selenium.ie.InternetExplorerDriver.<init>(InternetExplorerDriver.java:172)
	at org.openqa.selenium.ie.InternetExplorerDriver.<init>(InternetExplorerDriver.java:148)
	at com.github.webdriverextensions.junitrunner.WebDriverRunner$BrowserConfiguration.createDriver(WebDriverRunner.java:613)
	at com.github.webdriverextensions.junitrunner.WebDriverRunner$BrowserConfiguration.access$400(WebDriverRunner.java:490)
	at com.github.webdriverextensions.junitrunner.WebDriverRunner.runChild(WebDriverRunner.java:293)
	at com.github.webdriverextensions.junitrunner.WebDriverRunner.runChild(WebDriverRunner.java:103)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

Driver Version: tried with 3.4.0.0 32/64, 3.3.1 - 32/64 bit IE server. But no luck

Thanks

**Comment by andidev** [comment]
I think you need to configure your Internet Explorer security settings before you can run it with selenium.
Could you try configure Internet Explorer according to this stackoverflow answer? 
http://stackoverflow.com/questions/14952348/not-able-to-launch-ie-browser-using-selenium2-webdriver-with-java

Does it solve your issues?

**Comment by ramkumary** [comment]
Thanks. But strangely,  I supplied desired capabilities as JSON string instead of Class., It is working. I am clueless to identify the issue here. This is only happening with IE.

**Comment by andidev** [comment]
Strange, I'll have a look at it as soon as I have time

**Comment by andidev** [comment]
BTW could you provide the working desired capabilities  json string?

**Comment by ramkumary** [comment]
Here is the working capabilities 

`@InternetExplorer(desiredCapabilities = "{ignoreProtectedModeSettings:true}")`

**Comment by andidev** [comment]
Oh now I see what is going on here. You need set the capabilities you have instantiated with the `setCapabilities(...)`-method in the constructor.

like this:
```java
public class InternetExplorerCapabilities extends DesiredCapabilities {
	private static final long serialVersionUID = -7497157939360194853L;
	final static String IE_WEBDRIVER_BINARY_PATH_PROPERTY = "webdriver.ie.driver";
	public InternetExplorerCapabilities() {
		DesiredCapabilities standardCapabilities = DesiredCapabilities.internetExplorer();
		standardCapabilities.setCapability(InternetExplorerDriver.INTRODUCE_FLAKINESS_BY_IGNORING_SECURITY_DOMAINS,
				true);
		standardCapabilities.setCapability(InternetExplorerDriver.UNEXPECTED_ALERT_BEHAVIOR, "ignore");
		standardCapabilities.setCapability(InternetExplorerDriver.ENABLE_PERSISTENT_HOVERING, false);
		standardCapabilities.setCapability(InternetExplorerDriver.IE_ENSURE_CLEAN_SESSION, true);
		System.setProperty(IE_WEBDRIVER_BINARY_PATH_PROPERTY, "drivers/internetexplorerdriver-windows-32bit.exe");
		setCapability(InternetExplorerOptions.IE_OPTIONS, standardCapabilities);

	}
}
```

does it work with this?

**Comment by ramkumary** [comment]
No Luck. Here is the exception.

`InternetExplorerOptions cannot be resolved to a variable`

**Comment by andidev** [comment]
Okey of course it does not work, this should work for you:
```java
package your.package

import org.openqa.selenium.ie.InternetExplorerDriver;
import org.openqa.selenium.remote.DesiredCapabilities;

public class InternetExplorerCapabilities extends DesiredCapabilities {

    public InternetExplorerCapabilities() {
        setCapability(InternetExplorerDriver.INTRODUCE_FLAKINESS_BY_IGNORING_SECURITY_DOMAINS, true);
        setCapability(InternetExplorerDriver.UNEXPECTED_ALERT_BEHAVIOR, "ignore");
        setCapability(InternetExplorerDriver.ENABLE_PERSISTENT_HOVERING, false);
        setCapability(InternetExplorerDriver.IE_ENSURE_CLEAN_SESSION, true);
    }

}
```

Please note that you don't need to set the driver path with
```java
System.setProperty(IE_WEBDRIVER_BINARY_PATH_PROPERTY, "drivers/internetexplorerdriver-windows-32bit.exe");
```
if the driver is downloaded to the drivers folder located in the root with the webdriverextensions-maven-plugin. If you need to set it I would suggest you to use @DriverPath annotation instead.

**Comment by ramkumary** [comment]
Sweet Sweet. It did the magic. Thank you.
