### ISSUE TITLE
NPE with latest version: ZipFile.getZipEntry(ZipFile.java:566)

### ISSUE THREAD

**Issue by jansohn** [webdriverextensions/webdriverextensions#90]
I'm getting a NullPointerException with the latest version 3.5.0. Here's the stack trace from eclipse.log:

    !ENTRY org.eclipse.core.resources 4 2 2017-04-28 13:40:57.425
    !MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.core.resources".
    !STACK 0
    java.lang.NullPointerException
    	at java.util.zip.ZipFile.getZipEntry(ZipFile.java:566)
    	at java.util.zip.ZipFile.access$900(ZipFile.java:60)
    	at java.util.zip.ZipFile$ZipEntryIterator.next(ZipFile.java:524)
    	at java.util.zip.ZipFile$ZipEntryIterator.nextElement(ZipFile.java:499)
    	at java.util.zip.ZipFile$ZipEntryIterator.nextElement(ZipFile.java:480)
    	at org.eclipse.m2e.jdt.internal.BuildPathManager.getJavaDocPathInArchive(BuildPathManager.java:692)
    	at org.eclipse.m2e.jdt.internal.BuildPathManager.getJavaDocUrl(BuildPathManager.java:677)
    	at org.eclipse.m2e.jdt.internal.BuildPathManager.getJavaDocUrl(BuildPathManager.java:670)
    	at org.eclipse.m2e.jdt.internal.BuildPathManager.configureAttchedSourcesAndJavadoc(BuildPathManager.java:306)
    	at org.eclipse.m2e.jdt.internal.BuildPathManager.getClasspath(BuildPathManager.java:255)
    	at org.eclipse.m2e.jdt.internal.BuildPathManager.getClasspath(BuildPathManager.java:363)
    	at org.eclipse.m2e.jdt.internal.BuildPathManager.getClasspath(BuildPathManager.java:343)
    	at org.eclipse.m2e.jdt.internal.BuildPathManager.getClasspath(BuildPathManager.java:371)
    	at org.eclipse.m2e.jdt.internal.BuildPathManager.updateClasspath(BuildPathManager.java:191)
    	at org.eclipse.m2e.jdt.internal.BuildPathManager.mavenProjectChanged(BuildPathManager.java:180)
    	at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.notifyProjectChangeListeners(ProjectRegistryManager.java:783)
    	at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.applyMutableProjectRegistry(ProjectRegistryManager.java:930)
    	at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.refresh(ProjectRegistryManager.java:300)
    	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod.getProjectFacade(MavenBuilder.java:154)
    	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod$1.call(MavenBuilder.java:89)
    	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:176)
    	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:151)
    	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:99)
    	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod.execute(MavenBuilder.java:86)
    	at org.eclipse.m2e.core.internal.builder.MavenBuilder.build(MavenBuilder.java:200)
    	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:735)
    	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
    	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
    	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
    	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:301)
    	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
    	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:304)
    	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:360)
    	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:383)
    	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:144)
    	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:235)
    	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
    
    !ENTRY org.eclipse.core.resources 4 75 2017-04-28 13:40:57.430
    !MESSAGE Errors occurred during the build.
    !SUBENTRY 1 org.eclipse.m2e.core 4 75 2017-04-28 13:40:57.430
    !MESSAGE Errors running builder 'Maven Project Builder' on project 'testautomation'.
    !STACK 0
    java.lang.NullPointerException
    	at java.util.zip.ZipFile.getZipEntry(ZipFile.java:566)
    	at java.util.zip.ZipFile.access$900(ZipFile.java:60)
    	at java.util.zip.ZipFile$ZipEntryIterator.next(ZipFile.java:524)
    	at java.util.zip.ZipFile$ZipEntryIterator.nextElement(ZipFile.java:499)
    	at java.util.zip.ZipFile$ZipEntryIterator.nextElement(ZipFile.java:480)
    	at org.eclipse.m2e.jdt.internal.BuildPathManager.getJavaDocPathInArchive(BuildPathManager.java:692)
    	at org.eclipse.m2e.jdt.internal.BuildPathManager.getJavaDocUrl(BuildPathManager.java:677)
    	at org.eclipse.m2e.jdt.internal.BuildPathManager.getJavaDocUrl(BuildPathManager.java:670)
    	at org.eclipse.m2e.jdt.internal.BuildPathManager.configureAttchedSourcesAndJavadoc(BuildPathManager.java:306)
    	at org.eclipse.m2e.jdt.internal.BuildPathManager.getClasspath(BuildPathManager.java:255)
    	at org.eclipse.m2e.jdt.internal.BuildPathManager.getClasspath(BuildPathManager.java:363)
    	at org.eclipse.m2e.jdt.internal.BuildPathManager.getClasspath(BuildPathManager.java:343)
    	at org.eclipse.m2e.jdt.internal.BuildPathManager.getClasspath(BuildPathManager.java:371)
    	at org.eclipse.m2e.jdt.internal.BuildPathManager.updateClasspath(BuildPathManager.java:191)
    	at org.eclipse.m2e.jdt.internal.BuildPathManager.mavenProjectChanged(BuildPathManager.java:180)
    	at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.notifyProjectChangeListeners(ProjectRegistryManager.java:783)
    	at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.applyMutableProjectRegistry(ProjectRegistryManager.java:930)
    	at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.refresh(ProjectRegistryManager.java:300)
    	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod.getProjectFacade(MavenBuilder.java:154)
    	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod$1.call(MavenBuilder.java:89)
    	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:176)
    	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:151)
    	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:99)
    	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod.execute(MavenBuilder.java:86)
    	at org.eclipse.m2e.core.internal.builder.MavenBuilder.build(MavenBuilder.java:200)
    	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:735)
    	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
    	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
    	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
    	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:301)
    	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
    	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:304)
    	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:360)
    	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:383)
    	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:144)
    	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:235)
    	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
    
    !ENTRY org.eclipse.core.jobs 4 2 2017-04-28 13:40:59.174
    !MESSAGE An internal error occurred during: "Download sources and javadoc".
    !STACK 0
    java.lang.NullPointerException
    	at java.util.zip.ZipFile.getZipEntry(ZipFile.java:566)
    	at java.util.zip.ZipFile.access$900(ZipFile.java:60)
    	at java.util.zip.ZipFile$ZipEntryIterator.next(ZipFile.java:524)
    	at java.util.zip.ZipFile$ZipEntryIterator.nextElement(ZipFile.java:499)
    	at java.util.zip.ZipFile$ZipEntryIterator.nextElement(ZipFile.java:480)
    	at org.eclipse.m2e.jdt.internal.BuildPathManager.getJavaDocPathInArchive(BuildPathManager.java:692)
    	at org.eclipse.m2e.jdt.internal.BuildPathManager.getJavaDocUrl(BuildPathManager.java:677)
    	at org.eclipse.m2e.jdt.internal.BuildPathManager.getJavaDocUrl(BuildPathManager.java:670)
    	at org.eclipse.m2e.jdt.internal.BuildPathManager.configureAttchedSourcesAndJavadoc(BuildPathManager.java:306)
    	at org.eclipse.m2e.jdt.internal.BuildPathManager.getClasspath(BuildPathManager.java:255)
    	at org.eclipse.m2e.jdt.internal.BuildPathManager.getClasspath(BuildPathManager.java:363)
    	at org.eclipse.m2e.jdt.internal.BuildPathManager.getClasspath(BuildPathManager.java:343)
    	at org.eclipse.m2e.jdt.internal.BuildPathManager.getClasspath(BuildPathManager.java:371)
    	at org.eclipse.m2e.jdt.internal.BuildPathManager.updateClasspath(BuildPathManager.java:191)
    	at org.eclipse.m2e.jdt.internal.DownloadSourcesJob.run(DownloadSourcesJob.java:176)
    	at org.eclipse.m2e.jdt.internal.DownloadSourcesJob$1.call(DownloadSourcesJob.java:136)
    	at org.eclipse.m2e.jdt.internal.DownloadSourcesJob$1.call(DownloadSourcesJob.java:1)
    	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:176)
    	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:151)
    	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:99)
    	at org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:1355)
    	at org.eclipse.m2e.jdt.internal.DownloadSourcesJob.run(DownloadSourcesJob.java:134)
    	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

**Comment by andidev** [comment]
When do you get this error? I don't see any webdriverextensions package in the stacktrace.

**Comment by jansohn** [comment]
As soon as I change the version in my POM and save the file. This will trigger m2e to update the artifact. Older versions work fine so I'm guessing something has changed with the new release.

**Comment by andidev** [comment]
Does 'mvn clean install' work from console?

**Comment by jansohn** [comment]
Yeah sure, it's only in combination with m2e. I'm not sure it's something you need to fix on your side as the artifacts are downloaded correctly. Should I close this issue as the actual problem is probably on m2e's side?

**Comment by andidev** [comment]
Most probably an m2e issue. Have you tried clearing the workspace or reimporting the artifacts or something similar to that? I'm no eclipse user so I'm not sure if that is possible.

**Comment by jansohn** [comment]
I have tried it on a different system with the same results. Thanks for the quick response.

**Comment by jansohn** [comment]
It's a Selenium 3.4.0 problem: https://github.com/SeleniumHQ/selenium/issues/3895
