### ISSUE TITLE
@DriverPaths annotation not working anymore with Selenium 3.4.0

### ISSUE THREAD

**Issue by jansohn** [webdriverextensions/webdriverextensions#91]
Seems like the `@DriverPaths` annotation does not work anymore with Selenium 3.4.0. With 3.3.1 it opens Firefox.

    @DriverPaths(firefox = "C:/Users/XYZ/Tools/FirefoxPortable/App/Firefox/firefox.exe")

Stacktrace:

    org.openqa.selenium.WebDriverException: Cannot find firefox binary in PATH. Make sure firefox is installed. OS appears to be: VISTA
    Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
    System info: host: 'XYZ', ip: '123.123.123.123', os.name: 'Windows 7', os.arch: 'x86', os.version: '6.1', java.version: '1.8.0_71'
    Driver info: driver.version: FirefoxDriver
            at org.openqa.selenium.firefox.FirefoxBinary.<init>(FirefoxBinary.java:115)
            at java.util.Optional.orElseGet(Optional.java:267)
            at org.openqa.selenium.firefox.FirefoxDriver.toExecutor(FirefoxDriver.java:204)
            at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:108)
            at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:137)
            at com.github.webdriverextensions.junitrunner.WebDriverRunner$BrowserConfiguration.createDriver(WebDriverRunner.java:604)
            at com.github.webdriverextensions.junitrunner.WebDriverRunner$BrowserConfiguration.access$400(WebDriverRunner.java:490)
            at com.github.webdriverextensions.junitrunner.WebDriverRunner.runChild(WebDriverRunner.java:293)
            at com.github.webdriverextensions.junitrunner.WebDriverRunner.runChild(WebDriverRunner.java:103)
            at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
            at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
            at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
            at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
            at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
            at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
            at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
            at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
            at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
            at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
            at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
            at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
            at java.lang.reflect.Method.invoke(Method.java:497)
            at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
            at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
            at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
            at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
            at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

With `desiredCapabilities` it's working:

    @Firefox(desiredCapabilities = "{\"moz:firefoxOptions\": { \"binary\": \"C:/Users/XYZ/Tools/FirefoxPortable/App/Firefox/firefox.exe\" } }")

**Comment by andidev** [comment]
I think you are confusing the driver path with the binary path. 
All @DriverPath(firefox="/path/to/driver") does is setting the system property with `System.setProperty("webdriver.gecko.driver", "/path/to/driver");` which should be the location of the [Gecko Driver](https://github.com/mozilla/geckodriver/releases).

Maybe there should be a way to set the the binary path through an annotation as well. e.g. @BinaryPath(firefox="/path/to/binary").

Not sure why it worked for you with Selenium 3.3.1. According to the [selenium changelog](https://github.com/SeleniumHQ/selenium/blob/master/dotnet/CHANGELOG) they seem to have made som changes to FirefoxDriver options and capabilities. Maybe thats what was causing it to work for version 3.3.1.

**Comment by andidev** [comment]
btw what version of firefox are you using?

**Comment by jansohn** [comment]
Oh OK, thanks for clearing that up! I'm using the latest Firefox v53.0.
