### ISSUE TITLE
ImmutableCapabilities Exception thrown for IE

### ISSUE THREAD

**Issue by ramkumary** [webdriverextensions/webdriverextensions#94]
I tried with desiredCapabilities JSON and Class. It was ended up with the following exception.

```
java.lang.NoClassDefFoundError: org/openqa/selenium/ImmutableCapabilities
	at org.openqa.selenium.ie.InternetExplorerDriver.<init>(InternetExplorerDriver.java:206)
	at org.openqa.selenium.ie.InternetExplorerDriver.<init>(InternetExplorerDriver.java:158)
	at com.github.webdriverextensions.junitrunner.WebDriverRunner$BrowserConfiguration.createDriver(WebDriverRunner.java:613)
	at com.github.webdriverextensions.junitrunner.WebDriverRunner$BrowserConfiguration.access$400(WebDriverRunner.java:490)
	at com.github.webdriverextensions.junitrunner.WebDriverRunner.runChild(WebDriverRunner.java:293)
	at com.github.webdriverextensions.junitrunner.WebDriverRunner.runChild(WebDriverRunner.java:103)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: java.lang.ClassNotFoundException: org.openqa.selenium.ImmutableCapabilities
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 18 more
```

It looks like InternetExplorerOptions is deprecated. Here is the code.

```
@Deprecated
  public InternetExplorerDriver(int port) {
    this(null, null, port);
  }

  /**
   * @deprecated Create an {@link InternetExplorerDriverService} and then use that to create a
   *   {@link RemoteWebDriver#RemoteWebDriver(org.openqa.selenium.remote.CommandExecutor, Capabilities)} with a
   *   {@link DriverCommandExecutor}.
   */
  @Deprecated
  public InternetExplorerDriver(InternetExplorerDriverService service) {
    this(service, null, DEFAULT_PORT);
  }

  /**
   * @deprecated Create an {@link InternetExplorerDriverService} and then use that to create a
   *   {@link RemoteWebDriver#RemoteWebDriver(org.openqa.selenium.remote.CommandExecutor, Capabilities)} with a
   *   {@link DriverCommandExecutor}.
   */
  @Deprecated
  public InternetExplorerDriver(InternetExplorerDriverService service, Capabilities capabilities) {
    this(service, capabilities, DEFAULT_PORT);
  }

  /**
   * @deprecated Create an {@link InternetExplorerDriverService} and then use that to create a
   *   {@link RemoteWebDriver#RemoteWebDriver(org.openqa.selenium.remote.CommandExecutor, Capabilities)} with a
   *   {@link DriverCommandExecutor}.
   */
  @Deprecated
  public InternetExplorerDriver(
      InternetExplorerDriverService service,
      Capabilities capabilities,
      int port) {
    if (capabilities == null) {
      capabilities = DesiredCapabilities.internetExplorer();
    }

    Preconditions.checkNotNull(capabilities);
    capabilities = new InternetExplorerOptions(capabilities)
        .merge(new ImmutableCapabilities(new HashMap<>()));

    if (service == null) {
      service = setupService(capabilities, port);
    }
    run(service, capabilities);
  }
```

**Comment by andidev** [comment]
Not sure why you get this error. InternetExplorerDriver is not deprecated, only the those constructors you are mentioning.

The error seems to be caused by a missing class org.openqa.selenium.ImmutableCapabilities in selenium. Which is strange since it should be there.

Which version of selenium are you using? How does your pom file look like?

**Comment by ramkumary** [comment]
I found an issue. It is my mistake. Thanks
